.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. vitalcoin_qt test_vitalcoin_qt
clean: FORCE
	$(MAKE) -C .. vitalcoin_qt_clean test_vitalcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_vitalcoin_qt_check
vitalcoin-qt vitalcoin-qt.exe: FORCE
	 $(MAKE) -C .. vitalcoin_qt
